name: Run Python Tests

on:
  push:
    branches:
      - main  # Cambia si quieres usar una rama diferente
  pull_request:
    branches:
      - main  # También puedes cambiar la rama aquí

jobs:
  test:
    runs-on: ubuntu-latest  # Usa un sistema Linux para el entorno

    strategy:
      matrix:
        python-version: [3.11, 3.12]  # Especifica las versiones de Python que quieres usar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Acción para clonar el repositorio

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Acción para configurar Python
        with:
          python-version: ${{ matrix.python-version }}  # Establece la versión de Python de la matriz

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Actualiza pip
          pip install -r requirements.txt || true  # Instala dependencias si tienes un archivo requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest tests.test  # Asegúrate de que el archivo tests.test es el correcto

